name: Lighthouse Build and Publish - therandomd

on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  build_publish_promote:
    runs-on:
      labels: self-hosted
      group: 7416-therandomdrunner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: katana-auth
        name: Authenticate with Katana
        uses: gdcorp-actions/katana-auth@v1

      - id: katana-app
        name: Get Katana App Info
        uses: gdcorp-actions/katana-get-app@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}

      - name: Golden Container Registry Login
        run: |
          aws ecr get-login-password --region us-west-2 | docker login 764525110978.dkr.ecr.us-west-2.amazonaws.com/alpine-node:20.6.1-alpine-3.18 -u AWS --password-stdin
      - name: Build Container
        run: |
          docker build -t ${{ steps.katana-app.outputs.app }}-image:${{ github.sha }} --build-arg NPM_AUTH_TOKEN=${{secrets.NPM_TOKEN}} .

      - id: katana-publish
        name: Publish Katana Artifact
        uses: gdcorp-actions/katana-publish-artifact@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}
          namespace: therandomd
          app: ${{ steps.katana-app.outputs.app }}
          image_name: ${{ steps.katana-app.outputs.app }}-image:${{ github.sha }}
          artifact_kind: ecs
          artifact_options_json: |
            {
              "ports": [8080,8443],
              "healthCheck": "/healthcheck"
            }
      - name: Promote to dev-private Environment
        uses: gdcorp-actions/katana-promote-artifact@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}
          namespace: therandomd
          app: ${{ steps.katana-app.outputs.app }}
          environment: dev
          artifact_id: ${{ steps.katana-publish.outputs.artifact_id }}
