# This workflow is geared toward running cirrus-scan from a GitHub cloud repo. It uses IAM DeployUser credentials instead of okta.
name: cirrus-scan

on:
  # Run after the 'Tests' workflow completes on the repo's default branch. Change this to suit your the CI workflows adopted by your team.
  workflow_run:
    workflows:
      - main
    branches:
      - $default-branch
    types:
      - completed
  push:
    paths:
      # Run when the workflow file itself is updated
      - '.github/workflows/cirrus-scan-zaproxy.yaml'
  workflow_dispatch:

jobs:
  cirrus-scan-dev:
    runs-on:
      labels: self-hosted
      group: 6429-hadoopmigratione

    # Config env vars as necessary for the job.
    env:
      AWS_REGION: us-west-2
    # Only run if previous workflow is successful (e.g., tests are green) or it's another event that qualifies.
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e97d7fbc8e0e5af69631c13daa0f4b5a8d88165b # v1.5.5
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::255575434142:user/GD-AWS-DeployUser-CKPEtlBatch-Dev-Private 
          role-duration-seconds: 7200 # 2 hours
          role-session-name: GD-AWS-DeployUser-CKPEtlBatch-Dev-Private

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@b9c809dc38d74cd0fde3c13cc4fe4ac72ebecdae # 2.2.2
        with:
          registries: ${{ secrets.AUDIT_ACCOUNT_ID }} # See https://github.com/gdcorp-appservices/cirrus-scan-cicd#cirrusscan-container-images for AUDIT_ACCOUNT_ID

      - name: Pull latest CirrusScan container image
        run: |
          docker pull ${{ secrets.AUDIT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd:latest
      # PAT supplied to GITHUB_AUTH below needs full repo access. cirrus-scan-cicd uses it to submit GitHub status webhook.
      - name: Run CirrusScan checks
        run: |
          docker run --rm \
          -e AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN \
          -e AWS_DEFAULT_REGION \
          -e TASK_LIST='["vulnscan","zaproxy"]' \
          -e GITHUB_URL=${GITHUB_SERVER_URL} \
          -e GITHUB_AUTH=${{ secrets.PAT_TOKEN }} \
          -e GITHUB_REPO=${GITHUB_REPOSITORY} \
          -e GITHUB_COMMIT=${GITHUB_SHA} \
          ${{ secrets.AUDIT_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com/cirrus-scan-cicd
