name: Dev Deploy ckpetlbatch

on:
  workflow_dispatch:
jobs:
  build_publish_promote:
    runs-on:
      labels: self-hosted
      group: 6429-hadoopmigratione

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - id: katana-auth
        name: Authenticate with Katana
        uses: gdcorp-actions/katana-auth@v1

      - id: katana-app
        name: Get Katana App Info
        uses: gdcorp-actions/katana-get-app@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}

      - name: Golden Container Registry Login
        run: |
          aws ecr get-login-password --region us-west-2 | docker login 764525110978.dkr.ecr.us-west-2.amazonaws.com -u AWS --password-stdin
      - name: Build Container
        run: |
          docker build --build-arg NPM_AUTH_TOKEN=${{secrets.NPM_TOKEN}} --build-arg THE_ENV=development -t ${{ steps.katana-app.outputs.app }}-image:${{ github.sha }} .

      - id: katana-publish
        name: Publish Katana Artifact
        uses: gdcorp-actions/katana-publish-artifact@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}
          namespace: ckpetlbatch
          app: ${{ steps.katana-app.outputs.app }}
          image_name: ${{ steps.katana-app.outputs.app }}-image:${{ github.sha }}
          artifact_kind: ecs
          artifact_options_json: |
            {
              "ports": [8080,8443],
              "healthcheckPath": "/healthcheck"
            }
      - name: Promote to dev-private Environment
        uses: gdcorp-actions/katana-promote-artifact@v1
        with:
          jwt: ${{ steps.katana-auth.outputs.jwt }}
          namespace: ckpetlbatch
          app: ${{ steps.katana-app.outputs.app }}
          environment: dev-private-1
          artifact_id: ${{ steps.katana-publish.outputs.artifact_id }}
