# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

    version: 2

    registries:
    Artifactory:
        type: npm-registry
        url: https://gdartifactory1.jfrog.io/artifactory/api/npm/node-virt/
        token: ${{secrets.JFROG_AUTH_TOKEN }}
    updates:
    - package-ecosystem: "npm"
    directory: "/"
    registries:
    - Artifactory
    schedule:
    interval: "weekly"
    day: "tuesday"
    time: "05:30"
    target-branch: "master"
    - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
    interval: "weekly"
    day: "tuesday"
    time: "05:30"
    target-branch: "master"
    open-pull-requests-limit: 5
    reviewers:
    - "wsb-teams"
    commit-message:
    # Prefix all commit messages with "[github actions] " (no colon, but a trailing whitespace)
    prefix: "[dependaBot] "
    # Specify labels for pull requests
    labels:
    - "github actions"
    - "dependencies"
    groups:
    dependencies:
        patterns:
        - "*"